services:
  - type: web
    name: skillsphere-backend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8085
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DRIVER
        value: com.mysql.cj.jdbc.Driver
