services:
  - type: web
    name: skillsphere-backend
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8085
      - key: DB_URL
        value: jdbc:h2:mem:skillsphere;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - key: DB_USERNAME
        value: sa
      - key: DB_PASSWORD
        value: password
      - key: DB_DRIVER
        value: org.h2.Driver
